/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/dev/rock.glb -s -T 
Files: public/dev/rock.glb [1.66MB] > D:\Web_Projects\Websites\_Anim\anim-skelly-vs-demon\rock-transformed.glb [40.1KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.RockCube.geometry} material={materials.base_material} />
    </group>
  )
}

useGLTF.preload('/rock-transformed.glb')
