/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/rock.glb -s -T 
Files: public/rock.glb [3.12MB] > D:\Web_Projects\Websites\_Anim\anim-skelly-vs-demon\rock-transformed.glb [215.47KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rock-transformed.glb')
  console.log(nodes.RockCube.geometry, materials.base_material)
  
  return (
    <group {...props} dispose={null}>
      <mesh 
        receiveShadow 
        geometry={nodes.RockCube.geometry} 
        material={materials.base_material} 
      />
    </group>
  )
}

useGLTF.preload('/rock-transformed.glb')
