/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/scene1.glb -s -T 
Files: public/scene1.glb [17.07MB] > D:\Web_Projects\Websites\_Anim\anim-skelly-vs-demon\scene1-transformed.glb [2.58MB] (85%)
*/

import { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene1-transformed.glb')
  const { actions } = useAnimations(animations, group)

  return(
    <group ref={group} {...props} dispose={null}>
     <group name="Scene">

     </group>
    </group>
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
        </group>
        <group name="rig001">
          <primitive object={nodes.root_1} />
          <primitive object={nodes['MCH-torsoparent_1']} />
          <primitive object={nodes['MCH-hand_ikparentL_1']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL_1']} />
          <primitive object={nodes['MCH-hand_ikparentR_1']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR_1']} />
          <primitive object={nodes['MCH-foot_ikparentL_1']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL_1']} />
          <primitive object={nodes['MCH-foot_ikparentR_1']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR_1']} />
        </group>
        <primitive object={nodes.neutral_bone} />
        <mesh name="RockCube" castShadow receiveShadow geometry={nodes.RockCube.geometry} material={materials.base_material} />
        <skinnedMesh name="DemonBody" geometry={nodes.DemonBody.geometry} material={materials['base_material.002']} skeleton={nodes.DemonBody.skeleton} />
        <skinnedMesh name="SkelBody" geometry={nodes.SkelBody.geometry} material={materials['base_material.003']} skeleton={nodes.SkelBody.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene1-transformed.glb')
