/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/skel.glb -s -T 
Files: public/skel.glb [7.47MB] > D:\Web_Projects\Websites\_Anim\anim-skelly-vs-demon\skel-transformed.glb [1.18MB] (84%)
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/skel-transformed.glb')
  const { actions } = useAnimations(animations, group)
  const [currentAnim, setCurrentAnim] = useState(1)

  useEffect(()=>{
    const playAnim = () => {
      actions["t" + currentAnim].fadeOut(0.5)
      actions["t" + props.anim].reset().fadeIn(0.5).play()
      setCurrentAnim(props.anim)
    }
    playAnim()
  },[props.anim])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig001">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
        </group>
        <skinnedMesh 
        name="SkelBody" 
        geometry={nodes.SkelBody.geometry} 
        material={materials['base_material.003']} 
        skeleton={nodes.SkelBody.skeleton} 
        castShadow
        receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/skel-transformed.glb')
